package pachicojm.java_mysql_crud;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author lokod
 */
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.*;
import javax.swing.*;

public class java_crud extends javax.swing.JFrame {

    /**
     * Creates new form java_crud
     */
    public java_crud() {
        initComponents();
        Show_Users_In_JTable();
        this.setLocationRelativeTo(null);

        jTable_display.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Prevent automatic resizing
        jTable_display.setFillsViewportHeight(true); // Fill the vertical space
        jTable_display.setPreferredSize(new Dimension(370, 400)); // Set an initial size or adjust as needed        
        
        // Create a custom header renderer for JTable
        JTableHeader header = jTable_display.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setBackground(new Color(7, 35, 53)); // Header background color
                label.setForeground(new Color(220, 221, 223));     // Header text color
                label.setHorizontalAlignment(JLabel.CENTER); // Header text alignment
                return label;
            }
        });
        jTable_display.setTableHeader(header);
        
    }

    public Connection getConnection()
    {
        String jdbc_url = "jdbc:mysql://127.0.0.1/java_crud";
        String username = "root";
        String password = "";
        Connection con;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            con = DriverManager.getConnection(jdbc_url, username,password);
            return con;
        } 
       catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ArrayList<User> getUsersList()
    {
        ArrayList<User> usersList = new ArrayList<User>();
        Connection connection = getConnection();

        String query = "SELECT * FROM  `users` ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);

            User user;

            while(rs.next())
            {
                user = new User(rs.getInt("id"),rs.getString("firstname"),rs.getString("lastname"),rs.getInt("age"));
                usersList.add(user);
            }

        } 
            catch (Exception e) {
                 e.printStackTrace();
        }
        return usersList;
    }
    
    public void Show_Users_In_JTable(){
        ArrayList <User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel)jTable_display.getModel();
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++){
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getFirstName();
            row[2] = list.get(i).getLastName();
            row[3] = list.get(i).getAge();
            
            model.addRow(row);
        }
        
    }
    
    public void executeSQlQuery(String query, String message)
    {
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                // refresh jtable data
                DefaultTableModel model = (DefaultTableModel)jTable_display.getModel();
                model.setRowCount(0);
                Show_Users_In_JTable();

                JOptionPane.showMessageDialog(null, "Data " +message+ " Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not " +message);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jTextField_lastname = new javax.swing.JTextField();
        jTextField_age = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display = new javax.swing.JTable();
        jButtondelete = new javax.swing.JButton();
        jButton_insert = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 35, 53));
        jPanel1.setForeground(new java.awt.Color(220, 221, 223));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 221, 223));
        jLabel1.setText("Age:");

        jLabel2.setBackground(new java.awt.Color(220, 221, 223));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 221, 223));
        jLabel2.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 221, 223));
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 221, 223));
        jLabel4.setText("Last Name:");

        jTextField_firstname.setBackground(new java.awt.Color(7, 35, 53));
        jTextField_firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_firstname.setForeground(new java.awt.Color(220, 221, 223));
        jTextField_firstname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 175, 173), 2, true));
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });

        jTextField_id.setBackground(new java.awt.Color(7, 35, 53));
        jTextField_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_id.setForeground(new java.awt.Color(220, 221, 223));
        jTextField_id.setAutoscrolls(false);
        jTextField_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 175, 173), 2, true));
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jTextField_lastname.setBackground(new java.awt.Color(7, 35, 53));
        jTextField_lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_lastname.setForeground(new java.awt.Color(220, 221, 223));
        jTextField_lastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 175, 173), 2, true));
        jTextField_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastnameActionPerformed(evt);
            }
        });

        jTextField_age.setBackground(new java.awt.Color(7, 35, 53));
        jTextField_age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_age.setForeground(new java.awt.Color(220, 221, 223));
        jTextField_age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 175, 173), 2, true));
        jTextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ageActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(7, 35, 53));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(220, 221, 223));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable_display.setAutoCreateRowSorter(true);
        jTable_display.setBackground(new java.awt.Color(7, 35, 53));
        jTable_display.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_display.setForeground(new java.awt.Color(220, 221, 223));
        jTable_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_display.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_display.setFocusable(false);
        jTable_display.setGridColor(new java.awt.Color(0, 175, 173));
        jTable_display.setRowSelectionAllowed(true);
        jTable_display.setSelectionBackground(new java.awt.Color(0, 175, 173));
        jTable_display.setSelectionForeground(new java.awt.Color(220, 221, 223));
        jTable_display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_display.setShowGrid(true);
        jTable_display.setSurrendersFocusOnKeystroke(true);
        jTable_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_displayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display);

        jButtondelete.setBackground(new java.awt.Color(0, 175, 173));
        jButtondelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtondelete.setForeground(new java.awt.Color(220, 221, 223));
        jButtondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-30.png"))); // NOI18N
        jButtondelete.setText("Delete");
        jButtondelete.setBorder(null);
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButton_insert.setBackground(new java.awt.Color(0, 175, 173));
        jButton_insert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_insert.setForeground(new java.awt.Color(220, 221, 223));
        jButton_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-30.png"))); // NOI18N
        jButton_insert.setText("Insert");
        jButton_insert.setBorder(null);
        jButton_insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_insertMouseClicked(evt);
            }
        });
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });

        jButton_update.setBackground(new java.awt.Color(0, 175, 173));
        jButton_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(220, 221, 223));
        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-30.png"))); // NOI18N
        jButton_update.setText("Update");
        jButton_update.setBorder(null);
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 175, 173));
        jLabel5.setText("@ PachicoJM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_id)
                            .addComponent(jTextField_firstname)
                            .addComponent(jTextField_lastname)
                            .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_age, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameActionPerformed

    private void jTextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ageActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        String query = "UPDATE `users` SET `firstname` = '" + jTextField_firstname.getText() + "', `lastname` = '" + jTextField_lastname.getText() + "', `age` = " + jTextField_age.getText() + " WHERE `id` = " + jTextField_id.getText();
        executeSQlQuery(query, "Updated");
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTable_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_displayMouseClicked
        // display selected row in jtextfields
        int i = jTable_display.getSelectedRow();
        TableModel model = jTable_display.getModel();
        jTextField_id.setText(model.getValueAt(i,0).toString());
        jTextField_firstname.setText(model.getValueAt(i,1).toString());
        jTextField_lastname.setText(model.getValueAt(i,2).toString());
        jTextField_age.setText(model.getValueAt(i,3).toString());
        
    }//GEN-LAST:event_jTable_displayMouseClicked

    private void jButton_insertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_insertMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_insertMouseClicked

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        String query = "INSERT INTO `users`(`firstname`, `lastname`, `age`) VALUES ('"+jTextField_firstname.getText()+"','"+jTextField_lastname.getText()+"',"+jTextField_age.getText()+")";
        
        executeSQlQuery(query, "Inserted");
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        String query = "DELETE FROM `users` WHERE id = "+jTextField_id.getText()+"";
                
        executeSQlQuery(query, "deleted");
    }//GEN-LAST:event_jButtondeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new java_crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_lastname;
    // End of variables declaration//GEN-END:variables
}
