/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pachicojm.java_mysql_login_register;

import java.awt.geom.RoundRectangle2D;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.*;
import org.mindrot.jbcrypt.BCrypt;

public class admin_account_manager extends javax.swing.JFrame {

    public admin_account_manager() {
        initComponents();
        
        // center the form
        setLocationRelativeTo(null);
        
        // rounded corners
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 10, 10)); 
        
        // setIcon as resized icon using resizeIcon method
        icon.setIcon(resizeIcon("/logo-light.png", 45, 40));
        jButton_insert.setIcon(resizeIcon("/icons8-add.png", 30, 30));
        jButton_update.setIcon(resizeIcon("/icons8-update.png", 30, 30));
        jButton_delete.setIcon(resizeIcon("/icons8-delete.png", 30, 30));
        jLabel_logout.setIcon(resizeIcon("/icons8-logout.png", 24, 24));
        
        // Add padding to the text and password fields
        jTextField_username.setBorder(new EmptyBorder(0, 5, 0, 0));
        jTextField_firstname.setBorder(new EmptyBorder(0, 5, 0, 0)); 
        jTextField_lastname.setBorder(new EmptyBorder(0, 5, 0, 0));
        jTextField_email.setBorder(new EmptyBorder(0, 5, 0, 0));
        jTextField_phone_number.setBorder(new EmptyBorder(0, 5, 0, 0)); 
        jPasswordField_password.setBorder(new EmptyBorder(0, 5, 0, 0));
        
        // method to show users
        Show_Users_In_JTable();
        
       
    }
    
    private Icon resizeIcon(String resourcePath, int width, int height) {
        ImageIcon icon = new ImageIcon(getClass().getResource(resourcePath));
        Image originalImage = icon.getImage();
        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }
    
    public void Show_Users_In_JTable() {
        DefaultTableModel model = (DefaultTableModel) jTable_display.getModel();
        model.setRowCount(0);

        try (Connection connection = myConnection.getConnection();
             Statement statement = connection.createStatement()) {

            String query = "SELECT * FROM `accountstbl`";
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String firstname = resultSet.getString("firstname");
                String lastname = resultSet.getString("lastname");
                String email = resultSet.getString("email");
                int phone = resultSet.getInt("phone");
                String username = resultSet.getString("username");
                String password = resultSet.getString("password");
                String usertype = resultSet.getString("usertype");

                model.addRow(new Object[]{id, firstname, lastname, email, phone, username, password, usertype});
            }

            resultSet.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void executeSQlQuery(String query, String message) {
        try (Connection connection = myConnection.getConnection();
             Statement statement = connection.createStatement()) {

            int result = statement.executeUpdate(query);
            if (result == 1) {
                DefaultTableModel model = (DefaultTableModel) jTable_display.getModel();
                model.setRowCount(0);
                Show_Users_In_JTable();
                JOptionPane.showMessageDialog(null, "Data " + message + " Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titlebar = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_lastname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_phone_number = new javax.swing.JTextField();
        jButton_insert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display = new javax.swing.JTable();
        jComboBox_usertype = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 400));
        getContentPane().setLayout(null);

        jPanel_titlebar.setBackground(new java.awt.Color(25, 23, 22));
        jPanel_titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_titlebarMouseDragged(evt);
            }
        });
        jPanel_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_titlebarMousePressed(evt);
            }
        });

        jLabel_exit.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit.setText("x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 175, 46));
        jLabel3.setText("Account");

        jLabel4.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manager");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-light.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin");

        jLabel_logout.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel_logout.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-logout.png"))); // NOI18N
        jLabel_logout.setText("-");
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titlebarLayout = new javax.swing.GroupLayout(jPanel_titlebar);
        jPanel_titlebar.setLayout(jPanel_titlebarLayout);
        jPanel_titlebarLayout.setHorizontalGroup(
            jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titlebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(140, 140, 140)
                .addComponent(jLabel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_exit)
                .addGap(20, 20, 20))
        );
        jPanel_titlebarLayout.setVerticalGroup(
            jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_titlebarLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_titlebar);
        jPanel_titlebar.setBounds(0, 0, 800, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 390));

        jLabel7.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel7.setText("First Name");

        jTextField_firstname.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_firstname.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jTextField_firstname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_firstname.setBorder(null);
        jTextField_firstname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_firstname.setPreferredSize(new java.awt.Dimension(180, 30));
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        jPasswordField_password.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField_password.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_password.setToolTipText("");
        jPasswordField_password.setPreferredSize(new java.awt.Dimension(180, 30));
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel11.setText("Last Name");

        jTextField_lastname.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_lastname.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jTextField_lastname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_lastname.setBorder(null);
        jTextField_lastname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_lastname.setPreferredSize(new java.awt.Dimension(180, 30));
        jTextField_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastnameActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel15.setText("Username");

        jTextField_username.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_username.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_username.setBorder(null);
        jTextField_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_username.setPreferredSize(new java.awt.Dimension(180, 30));
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(230, 175, 46));
        jButton_delete.setFont(new java.awt.Font("Inter ExtraBold", 0, 18)); // NOI18N
        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete.png"))); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.setIconTextGap(2);
        jButton_delete.setPreferredSize(new java.awt.Dimension(130, 40));
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_update.setBackground(new java.awt.Color(230, 175, 46));
        jButton_update.setFont(new java.awt.Font("Inter ExtraBold", 0, 18)); // NOI18N
        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update.png"))); // NOI18N
        jButton_update.setText("Update");
        jButton_update.setIconTextGap(2);
        jButton_update.setPreferredSize(new java.awt.Dimension(130, 40));
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel16.setText("User Type");

        jLabel17.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel17.setText("Email");

        jTextField_email.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_email.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jTextField_email.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_email.setBorder(null);
        jTextField_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_email.setPreferredSize(new java.awt.Dimension(180, 30));
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel14.setText("Phone");

        jTextField_phone_number.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_phone_number.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jTextField_phone_number.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_phone_number.setBorder(null);
        jTextField_phone_number.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_phone_number.setPreferredSize(new java.awt.Dimension(180, 30));
        jTextField_phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phone_numberActionPerformed(evt);
            }
        });

        jButton_insert.setBackground(new java.awt.Color(230, 175, 46));
        jButton_insert.setFont(new java.awt.Font("Inter ExtraBold", 0, 18)); // NOI18N
        jButton_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add.png"))); // NOI18N
        jButton_insert.setText("Insert");
        jButton_insert.setIconTextGap(2);
        jButton_insert.setPreferredSize(new java.awt.Dimension(130, 40));
        jButton_insert.setRolloverEnabled(false);
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(520, 440));

        jTable_display.setAutoCreateRowSorter(true);
        jTable_display.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        jTable_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Phone", "Username", "Password", "User Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_display.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_display.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jTable_display.setPreferredSize(new java.awt.Dimension(520, 440));
        jTable_display.setShowGrid(false);
        jTable_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_displayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display);
        jTable_display.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jComboBox_usertype.setFont(new java.awt.Font("Inter Light", 0, 18)); // NOI18N
        jComboBox_usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        jComboBox_usertype.setPreferredSize(new java.awt.Dimension(180, 30));
        jComboBox_usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_usertypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_phone_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_usertype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 800, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private int xMouse, yMouse;
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        // minimize window
        this.setState(admin_account_manager.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_titlebarMouseDragged
        // get x and y coordinates of mouse on the screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        // change the location of panel to x and y location of mouse
        setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel_titlebarMouseDragged

    private void jPanel_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_titlebarMousePressed
        // get x and y coordinates of mouse
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_titlebarMousePressed

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jTextField_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jTextField_phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phone_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phone_numberActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
      
        int i = jTable_display.getSelectedRow();
        if (i == -1) {
            // No row selected, display an error message
            JOptionPane.showMessageDialog(null, "No row selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // or use 'break' if inside a loop
        }

        TableModel model = jTable_display.getModel();
        String id = model.getValueAt(i, 0).toString();

        // Ask for confirmation
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Clear the selection in the JTable
            jTable_display.clearSelection();

            String query = "DELETE FROM `accountstbl` where id = " + id;
            executeSQlQuery(query, "Deleted");
        } else {
            JOptionPane.showMessageDialog(null, "Deletion canceled.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
          
        int i = jTable_display.getSelectedRow();
        if (i == -1) {
            // No row selected, display an error message
            JOptionPane.showMessageDialog(null, "No row selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // or use 'break' if inside a loop
        }

        TableModel model = jTable_display.getModel();
        String id = model.getValueAt(i, 0).toString();

        String firstname = jTextField_firstname.getText();
        String lastname = jTextField_lastname.getText();
        String email = jTextField_email.getText();
        String phone = jTextField_phone_number.getText();
        String username = jTextField_username.getText();
        char[] passwordChars = jPasswordField_password.getPassword();
        String password = new String(passwordChars);
        String usertype = (String) jComboBox_usertype.getSelectedItem();

        // Convert phone number to int
        int phoneNumber = Integer.parseInt(phone);

        // Get the existing password from the database
        String existingPassword = null; // Initialize the existing password

        try {
            // Use your existing database connection to prepare and execute the query
            Connection connection = myConnection.getConnection();
            String queryGetPassword = "SELECT `password` FROM `accountstbl` WHERE `id` = ?";

            // Prepare the query
            PreparedStatement statement = connection.prepareStatement(queryGetPassword);
            statement.setString(1, id); // Set the parameter for the WHERE clause

            // Execute the query
            ResultSet resultSet = statement.executeQuery();

            // Check if a result was found
            if (resultSet.next()) {
                existingPassword = resultSet.getString("password");
            }

            // Close resources
            resultSet.close();
            statement.close();
        } catch (Exception e) {
            e.printStackTrace();
            // Handle any exceptions that may occur during the database query
        }

        String query;

        if (!password.equals(existingPassword)) {
            // Hash and update the password only if it's different from the existing one
            String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());
            query = "UPDATE `accountstbl` SET `firstname` = '" + firstname + "', `lastname` = '" + lastname + "', `email` = '" + email + "', `phone` = " + phoneNumber + ", `username` = '" + username + "', `password` = '" + hashedPassword + "', `usertype` = '" + usertype + "' WHERE `id` = " + id;
        } else {
            query = "UPDATE `accountstbl` SET `firstname` = '" + firstname + "', `lastname` = '" + lastname + "', `email` = '" + email + "', `phone` = " + phoneNumber + ", `username` = '" + username + "', `usertype` = '" + usertype + "' WHERE `id` = " + id;
        }        

        executeSQlQuery(query, "Updated");
        
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        
        String firstname = jTextField_firstname.getText();
        String lastname = jTextField_lastname.getText();
        String email = jTextField_email.getText();
        String phone = jTextField_phone_number.getText();
        String username = jTextField_username.getText();
        String password = new String(jPasswordField_password.getPassword());
        String usertype = (String) jComboBox_usertype.getSelectedItem();
        
        // Check if any of the fields are empty
        if (firstname.isEmpty() || lastname.isEmpty() || email.isEmpty() || phone.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields are empty!.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Return early when any field is empty
        }
        
        // Convert phone number to int
        int phonenumber = Integer.parseInt(phone);

        // Hash the password using BCrypt
        String hashedpassword = BCrypt.hashpw(password, BCrypt.gensalt());

        // Use a prepared statement to avoid SQL injection
        String query = "INSERT INTO accountstbl (firstname, lastname, email, phone, username, password, usertype) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (Connection connection = myConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(query)) {

            statement.setString(1, firstname);
            statement.setString(2, lastname);
            statement.setString(3, email);
            statement.setInt(4, phonenumber);
            statement.setString(5, username);
            statement.setString(6, hashedpassword);
            statement.setString(7, usertype);
            
            // Clear the selection in the JTable
            jTable_display.clearSelection();

            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Inserted");
            
            Show_Users_In_JTable();

        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            // Handle the duplicate entry exception
            JOptionPane.showMessageDialog(null, "Username already exists. Please choose a different username.", "Duplicate Username", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle other SQL exceptions
            JOptionPane.showMessageDialog(null, "An error occurred during data insertion. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jComboBox_usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_usertypeActionPerformed

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked

        // Redirect the user to the sign-in page
        sign_in signIn = new sign_in();
        signIn.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jTable_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_displayMouseClicked
        
        // Check if a row is selected
        int i = jTable_display.getSelectedRow();
        if (i >= 0) {
            TableModel model = jTable_display.getModel();
            jTextField_firstname.setText(model.getValueAt(i, 1).toString());
            jTextField_lastname.setText(model.getValueAt(i, 2).toString());
            jTextField_email.setText(model.getValueAt(i, 3).toString());
            jTextField_phone_number.setText(model.getValueAt(i, 4).toString());
            jTextField_username.setText(model.getValueAt(i, 5).toString());
            jPasswordField_password.setText(model.getValueAt(i, 6).toString());
        } else {
            // Handle the case where no row is selected, for example, by clearing the text fields.
            jTextField_firstname.setText("");
            jTextField_lastname.setText("");
            jTextField_email.setText("");
            jTextField_phone_number.setText("");
            jTextField_username.setText("");
            jPasswordField_password.setText("");
        }

    }//GEN-LAST:event_jTable_displayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_account_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_account_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_account_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_account_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_account_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_usertype;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_titlebar;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_phone_number;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
