/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pachicojm.java_mysql_login_register;

import java.awt.geom.RoundRectangle2D;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.EmptyBorder;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.mindrot.jbcrypt.BCrypt;


public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public sign_up() {
        initComponents();
        
        // center the form
        setLocationRelativeTo(null);
        
        // rounded corners
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 10, 10));
        
        // setIcon as resized icon using resizeIcon method
        icon.setIcon(resizeIcon("/logo-light.png", 45, 40));
        image1.setIcon(resizeIcon("/online-yellow-world1.png", 410, 600));   

        // Add padding to the text and password fields
        jTextField_username.setBorder(new EmptyBorder(0, 5, 0, 0));
        jTextField_firstname.setBorder(new EmptyBorder(0, 5, 0, 0)); 
        jTextField_lastname.setBorder(new EmptyBorder(0, 5, 0, 0));
        jTextField_email.setBorder(new EmptyBorder(0, 5, 0, 0));
        jTextField_phone_number.setBorder(new EmptyBorder(0, 5, 0, 0)); 
        jPasswordField_password.setBorder(new EmptyBorder(0, 5, 0, 0));
        jPasswordField_confirmpass.setBorder(new EmptyBorder(0, 5, 0, 0));
        
    }
    
    private Icon resizeIcon(String resourcePath, int width, int height) {
        ImageIcon icon = new ImageIcon(getClass().getResource(resourcePath));
        Image originalImage = icon.getImage();
        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titlebar = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_sign_up = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_signin = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_lastname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField_confirmpass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_phone_number = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel_titlebar.setBackground(new java.awt.Color(25, 23, 22));
        jPanel_titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_titlebarMouseDragged(evt);
            }
        });
        jPanel_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_titlebarMousePressed(evt);
            }
        });

        jLabel_exit.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit.setText("x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 175, 46));
        jLabel3.setText("Up");

        jLabel4.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-light.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_titlebarLayout = new javax.swing.GroupLayout(jPanel_titlebar);
        jPanel_titlebar.setLayout(jPanel_titlebarLayout);
        jPanel_titlebarLayout.setHorizontalGroup(
            jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titlebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(289, 289, 289)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_exit)
                .addGap(15, 15, 15))
        );
        jPanel_titlebarLayout.setVerticalGroup(
            jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_titlebarLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_titlebar);
        jPanel_titlebar.setBounds(0, 0, 800, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton_sign_up.setBackground(new java.awt.Color(230, 175, 46));
        jButton_sign_up.setFont(new java.awt.Font("Inter ExtraBold", 0, 24)); // NOI18N
        jButton_sign_up.setText("SIGN UP");
        jButton_sign_up.setBorder(null);
        jButton_sign_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sign_upActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel7.setText("First Name");

        jTextField_firstname.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_firstname.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jTextField_firstname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_firstname.setBorder(null);
        jTextField_firstname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_firstname.setPreferredSize(new java.awt.Dimension(250, 40));
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        jLabel1.setFont(new java.awt.Font("Inter Light", 0, 12)); // NOI18N
        jLabel1.setText("By continuing, you agree to our Terms of Services.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel9.setText("Already have an account?");

        jLabel_signin.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel_signin.setForeground(new java.awt.Color(230, 175, 46));
        jLabel_signin.setText("Sign In!");
        jLabel_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_signinMouseClicked(evt);
            }
        });

        jPasswordField_password.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField_password.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_password.setToolTipText("");
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel11.setText("Last Name");

        jTextField_lastname.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_lastname.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jTextField_lastname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_lastname.setBorder(null);
        jTextField_lastname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_lastname.setPreferredSize(new java.awt.Dimension(250, 40));
        jTextField_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastnameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel12.setText("Confirm Pass");

        jPasswordField_confirmpass.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField_confirmpass.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jPasswordField_confirmpass.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_confirmpass.setToolTipText("");
        jPasswordField_confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_confirmpassActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel14.setText("Phone");

        jTextField_phone_number.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_phone_number.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jTextField_phone_number.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_phone_number.setBorder(null);
        jTextField_phone_number.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phone_numberActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel15.setText("Username");

        jTextField_username.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_username.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_username.setBorder(null);
        jTextField_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Inter Light", 0, 12)); // NOI18N
        jLabel5.setText("Read our Privacy Policy.");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel16.setText("Email");

        jTextField_email.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_email.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jTextField_email.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_email.setBorder(null);
        jTextField_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Inter SemiBold", 1, 48)); // NOI18N
        jLabel13.setText("Sign");

        jLabel6.setFont(new java.awt.Font("Inter SemiBold", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 175, 46));
        jLabel6.setText("Up");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jButton_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_signin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(22, 22, 22)
                .addComponent(jButton_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_signin))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 400, 560);

        jPanel4.setBackground(new java.awt.Color(248, 231, 193));

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online-yellow-world1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(400, 40, 400, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked
    
    // variable for x and y of mouse
    private int xMouse, yMouse;
    
    private void jPanel_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_titlebarMouseDragged
        // get x and y coordinates of mouse on the screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        // change the location of panel to x and y location of mouse
        setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel_titlebarMouseDragged

    private void jPanel_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_titlebarMousePressed
        // get x and y coordinates of mouse 
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_titlebarMousePressed

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed
    
    // create method for validation
    private boolean isValidName(String name) {
        // Regular expression to match letters only
        String regex = "^[a-zA-Z]+$";
        return name.matches(regex);
    }

    private boolean isValidEmail(String email) {
        // Regular expression to match email format
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        return email.matches(regex);
    }

    private boolean isValidPhoneNumber(String phone) {
        // Regular expression to match phone number format
        String regex = "^[0-9]{7,19}$";
        return phone.matches(regex);
    }
    
    private boolean checkUsername(String username) {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        
        String query = "SELECT * FROM `accountstbl` WHERE `username` = ?";
        
        try {
            ps = myConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            if(rs.next()){
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return checkUser;
    }
    
    private void jButton_sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sign_upActionPerformed
                                                                             
        // Get all values needed for signup
        String firstname = jTextField_firstname.getText();
        String lastname = jTextField_lastname.getText();
        String email = jTextField_email.getText();
        String phoneText = jTextField_phone_number.getText(); // Store as a string
        String username = jTextField_username.getText();
        String password = String.valueOf(jPasswordField_password.getPassword());
        String confirm_password = String.valueOf(jPasswordField_confirmpass.getPassword());

        // Make account type default
        String account_type = "User";

        // Password hashing
        String hashed_password = BCrypt.hashpw(password, BCrypt.gensalt());

        // Add validation
        if (firstname.equals("") || lastname.equals("") || email.equals("") || phoneText.equals("") || username.equals("") || password.equals("") || confirm_password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please complete all the required fields.");
            return; // Return early when validation fails
        }

        if (!password.equals(confirm_password)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match");
            return; // Return early when validation fails
        }

        if (!isValidName(firstname)) {
            JOptionPane.showMessageDialog(null, "Invalid first name. Only letters are allowed.");
            return; // Return early when validation fails
        }

        if (!isValidName(lastname)) {
            JOptionPane.showMessageDialog(null, "Invalid last name. Only letters are allowed.");
            return; // Return early when validation fails
        }

        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Invalid email address");
            return; // Return early when validation fails
        }

        // Check if the phoneText is empty before parsing
        if (phoneText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide a phone number.");
            return; // Return early when validation fails
        }

        // Attempt to parse the phone number
        int phone;
        try {
            phone = Integer.parseInt(phoneText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid phone number. Please enter a valid number.");
            return; // Return early when validation fails
        }

        if (checkUsername(username)) {
            JOptionPane.showMessageDialog(null, "This User Already Exists");
            return; // Return early when validation fails
        }

        PreparedStatement ps;
        String query = "INSERT INTO `accountstbl`(`firstname`, `lastname`, `email`, `phone`, `username`, `password`, `usertype`) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try {
            // Connect the query to the database
            ps = myConnection.getConnection().prepareStatement(query);

            // Add data to the database
            ps.setString(1, firstname);
            ps.setString(2, lastname);
            ps.setString(3, email);
            ps.setLong(4, phone);
            ps.setString(5, username);
            ps.setString(6, hashed_password);
            ps.setString(7, account_type);

            // Execute the query
            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Welcome New User");               
            } 

        } catch (SQLException ex) {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
    }//GEN-LAST:event_jButton_sign_upActionPerformed
  
    private void jTextField_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jPasswordField_confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_confirmpassActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jLabel_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signinMouseClicked
        
        // Go to sign_in
        sign_in signInFrame = new sign_in();
        signInFrame.setVisible(true);
        signInFrame.pack();
        signInFrame.setLocationRelativeTo(null);
        signInFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_signinMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        // minimize window
        this.setState(sign_up.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField_phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phone_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phone_numberActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton_sign_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_signin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_titlebar;
    private javax.swing.JPasswordField jPasswordField_confirmpass;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_phone_number;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
