/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pachicojm.java_mysql_login_register;

import java.awt.geom.RoundRectangle2D;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.EmptyBorder;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author lokod
 */
public class sign_in extends javax.swing.JFrame {

    /**
     * Creates new form signin
     */
    public sign_in() {
       // Initialize the form's components
        initComponents();

        // Center the form on the screen
        setLocationRelativeTo(null);

        // Create rounded corners for the form
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 10, 10));

        // Set the application icon with a resized image using the resizeIcon method
        icon.setIcon(resizeIcon("/logo-light.png", 45, 40));
        image1.setIcon(resizeIcon("/online-yellow-world1.png", 410, 600));

        // Add padding to the username and password input fields
        jTextField_username.setBorder(new EmptyBorder(0, 5, 0, 0));
        jPasswordField_password.setBorder(new EmptyBorder(0, 5, 0, 0));

    }
    
    private Icon resizeIcon(String resourcePath, int width, int height) {
        // Load the image icon from the specified resource path
        ImageIcon icon = new ImageIcon(getClass().getResource(resourcePath));

        // Get the original Image from the loaded icon
        Image originalImage = icon.getImage();

        // Scale the original image to the desired width and height using a smooth scaling algorithm
        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);

        // Create and return a new ImageIcon from the resized Image
        return new ImageIcon(resizedImage);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titlebar = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_sign_in = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_signup = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel_titlebar.setBackground(new java.awt.Color(25, 23, 22));
        jPanel_titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_titlebarMouseDragged(evt);
            }
        });
        jPanel_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_titlebarMousePressed(evt);
            }
        });

        jLabel_exit.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit.setText("x");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 175, 46));
        jLabel3.setText("In");

        jLabel4.setFont(new java.awt.Font("Inter SemiBold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-light.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_titlebarLayout = new javax.swing.GroupLayout(jPanel_titlebar);
        jPanel_titlebar.setLayout(jPanel_titlebarLayout);
        jPanel_titlebarLayout.setHorizontalGroup(
            jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titlebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(295, 295, 295)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_exit)
                .addGap(15, 15, 15))
        );
        jPanel_titlebarLayout.setVerticalGroup(
            jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_titlebarLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_titlebar);
        jPanel_titlebar.setBounds(0, 0, 800, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Inter SemiBold", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 175, 46));
        jLabel6.setText("In");

        jLabel5.setFont(new java.awt.Font("Inter SemiBold", 1, 48)); // NOI18N
        jLabel5.setText("Sign");

        jButton_sign_in.setBackground(new java.awt.Color(230, 175, 46));
        jButton_sign_in.setFont(new java.awt.Font("Inter ExtraBold", 0, 24)); // NOI18N
        jButton_sign_in.setText("SIGN IN");
        jButton_sign_in.setBorder(null);
        jButton_sign_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_sign_in.setPreferredSize(new java.awt.Dimension(300, 40));
        jButton_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sign_inActionPerformed(evt);
            }
        });
        jButton_sign_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_sign_inKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel9.setText("Don't have an account?");

        jLabel_signup.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel_signup.setForeground(new java.awt.Color(230, 175, 46));
        jLabel_signup.setText("Sign Up!");
        jLabel_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_signupMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        jLabel7.setText("Username");

        jTextField_username.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_username.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_username.setBorder(null);
        jTextField_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_username.setPreferredSize(new java.awt.Dimension(250, 40));
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        jLabel10.setText("Password");

        jPasswordField_password.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField_password.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_password.setToolTipText("");
        jPasswordField_password.setPreferredSize(new java.awt.Dimension(250, 40));

        jCheckBox1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Remember Me");
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setText("Forgot your password?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel1))
                        .addGap(75, 75, 75))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_signup))
                    .addComponent(jButton_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jButton_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_signup))
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 400, 560);

        jPanel4.setBackground(new java.awt.Color(248, 231, 193));

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online-yellow-world1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(400, 0, 400, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jButton_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sign_inActionPerformed
        
        PreparedStatement ps;
        ResultSet rs;

        String username = jTextField_username.getText();
        String password = String.valueOf(jPasswordField_password.getPassword());

        String query = "SELECT * FROM `accountstbl` WHERE `username` = ?";

        try {
            ps = myConnection.getConnection().prepareStatement(query);

            ps.setString(1, username);

            rs = ps.executeQuery();

            if (rs.next()) {
                String hashed_password = rs.getString("password");
                String userType = rs.getString("usertype");
                String firstname = rs.getString("firstname");

                if (BCrypt.checkpw(password, hashed_password)) {
                    if (userType == null) {
                        JOptionPane.showMessageDialog(null, "Unknown User Type");
                    } else {
                        switch (userType) {
                            case "User":
                                user_home uhf = new user_home();
                                uhf.setVisible(true);
                                uhf.pack();
                                uhf.setLocationRelativeTo(null);
                                uhf.setExtendedState(JFrame.EXIT_ON_CLOSE);
                                uhf.jLabel_firstname.setText(firstname);
                                this.dispose();
                                break;

                            case "Admin":
                                admin_account_manager aam = new admin_account_manager();
                                aam.setVisible(true);
                                aam.pack();
                                aam.setLocationRelativeTo(null);
                                aam.setExtendedState(JFrame.EXIT_ON_CLOSE);
                                this.dispose();
                                break;

                            default:
                                JOptionPane.showMessageDialog(null, "Unknown user type");
                                break;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect Password");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
            }

        } catch (SQLException ex) {
            Logger.getLogger(sign_in.class.getName()).log(Level.SEVERE, null, ex);
        }       
        
    }//GEN-LAST:event_jButton_sign_inActionPerformed
   
    // variable for x and y of mouse
    private int xMouse,yMouse;
    
    private void jPanel_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_titlebarMousePressed
        // get x and y coordinates of mouse 
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_titlebarMousePressed

    private void jPanel_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_titlebarMouseDragged
        // get x and y coordinates of mouse on the screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        // change the location of panel to x and y location of mouse
        setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel_titlebarMouseDragged

    private void jLabel_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signupMouseClicked
        
        // Go to sign_up
        sign_up rgf = new sign_up();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(sign_in.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_signupMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        // minimize window
        this.setState(sign_up.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton_sign_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_sign_inKeyPressed
        
    }//GEN-LAST:event_jButton_sign_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton_sign_in;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_signup;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_titlebar;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
